USE STREAMING_HIVE;
CREATE TABLE IF NOT EXISTS TASK_INFO
(
  ID VARCHAR(40) PRIMARY KEY,
  DB VARCHAR(50),
  TABLE_NAME VARCHAR(70),
  PARTITION_NAME VARCHAR(30),
  FILE_PATH VARCHAR(255),
  OP CHAR(1),
  STATUS VARCHAR(10),
  ATTEMPT INT INT DEFAULT 0,
  UPDATE_TIME TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATE_TIME TIMESTAMP NOT NULL,
  KEY INDEX_TASK_INFO (DB, TABLE_NAME, PARTITION_NAME)
)